// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qikwnosoefyowejciosr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpa3dub3NvZWZ5b3dlamNpb3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Mzc4NzgsImV4cCI6MjA2MDAxMzg3OH0.fzKSYhJKvqouoNezoTqoj5Ph00CTxy8iw6BZRbGRnDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);